export const metadata = {
    title: "Digital Wolf - career",
    description: "Generated by create next app",
  };
  export default function Layout({ children }) {
    return (
          <>
            <main>{children}</main>
          </>
    );
  }